In [1]:
import numpy as np

In [4]:
# 1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

array1 = np.random.randint(10,100,50)
array1

array([69, 70, 42, 67, 13, 61, 94, 62, 41, 22, 86, 28, 71, 30, 95, 55, 44,
       49, 25, 88, 95, 75, 42, 13, 48, 92, 36, 18, 12, 54, 89, 96, 34, 23,
       41, 54, 21, 82, 45, 83, 77, 46, 12, 67, 47, 43, 13, 86, 10, 79])

In [5]:
array1 [4::5]

array([13, 22, 95, 88, 48, 54, 41, 83, 47, 79])

In [14]:
# 2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

array2 = np.random.randint(1,21,30)
array2



array([ 7, 17, 14, 12,  2,  7, 16,  7, 13, 17,  6,  7, 17,  9, 18, 18, 17,
       13, 15,  2, 10, 11, 15,  7, 20,  2, 15, 14, 17, 14])

In [18]:
impares = array2[::2]
impares

array([ 7, 14,  2, 16, 13,  6, 17, 18, 17, 15, 10, 15, 20, 15, 17])

In [25]:
# 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

array2d = np.random.randint(0,10, (4,6))
array2d

array([[9, 7, 2, 2, 4, 2],
       [8, 9, 4, 8, 3, 3],
       [4, 2, 4, 0, 8, 8],
       [9, 0, 7, 2, 5, 5]])

In [27]:
array2d = array2d.astype(float)
array2d

array([[9., 7., 2., 2., 4., 2.],
       [8., 9., 4., 8., 3., 3.],
       [4., 2., 4., 0., 8., 8.],
       [9., 0., 7., 2., 5., 5.]])

In [28]:
array2d = array2d.astype(float)

In [30]:
array2round = np.round(array2d, 2)
array2round[-1]

array([9., 0., 7., 2., 5., 5.])

In [32]:
# 4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

array2b =np.random.rand(6,4).round(2)
array2b

array([[0.73, 0.34, 0.72, 0.4 ],
       [0.08, 0.6 , 0.65, 0.03],
       [0.84, 0.95, 0.8 , 0.94],
       [0.92, 0.25, 0.1 , 0.16],
       [0.8 , 0.54, 0.42, 0.31],
       [0.39, 0.12, 0.87, 0.32]])

In [33]:
array2b[:,1]

array([0.34, 0.6 , 0.95, 0.25, 0.54, 0.12])

In [34]:
# 5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

array1d5 = np.random.randint(-50, 51, 30)
array1d5

array([-35,   1,   0, -42,  -3,   4,   0,   0,   0, -27, -35,  16, -39,
        10,   5,  45,  30,  -9, -23, -44, -39,  36, -35,   8, -27,  31,
        18,  -7,   6,  38])

In [37]:
negativos = array1d5 [array1d5 < 0]
negativos

array([-35, -42,  -3, -27, -35, -39,  -9, -23, -44, -39, -35, -27,  -7])

In [38]:
# 6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. 
# Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

array10 = np.random.rand(10).round(2)
mayor = array10[array10 > 0.5]

In [40]:
array10

array([0.85, 0.89, 0.02, 0.86, 0.72, 0.8 , 0.69, 0.85, 0.72, 0.31])

In [41]:
mayor

array([0.85, 0.89, 0.86, 0.72, 0.8 , 0.69, 0.85, 0.72])

In [44]:
array10w = np.where(array10 > 0.5)
array10w

(array([0, 1, 3, 4, 5, 6, 7, 8]),)

In [52]:
# 7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

array7 = np.random.randint(1,101,40)
array7

array([19, 38, 77, 73, 26, 49, 15, 30,  2, 65, 86, 79, 29, 29,  9, 81, 65,
       30, 28, 97, 78, 30, 12, 35, 42, 90,  1, 80, 61, 93, 56, 63, 84, 76,
       60, 54, 41, 95, 43, 41])

In [55]:
divisible = array7[array7 % 3 == 0]
divisible

array([15, 30,  9, 81, 30, 78, 30, 12, 42, 90, 93, 63, 84, 60, 54])

In [60]:
divisible4 = array7[array7 % 4 == 0]
divisible4

array([28, 12, 80, 56, 84, 76, 60])

In [ ]:
# Reshape y Transpose

In [ ]:
# Ejercicios con reshape

In [61]:
# 1.Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). 
# Utiliza reshape para convertirlo en un array 2D. 
# Deberás pensar en la forma que es correcta para hacer este cambio.

array3D = np.random.randint (1,101,(2,3,4))
array3D

array([[[96, 78, 96, 32],
        [88, 18, 22, 93],
        [66, 68, 73,  9]],

       [[65, 41, 67,  2],
        [10, 55, 16, 25],
        [93, 94, 54, 69]]])

In [63]:
array2Dd = array3D.reshape(-1, 4)
array2Dd

array([[96, 78, 96, 32],
       [88, 18, 22, 93],
       [66, 68, 73,  9],
       [65, 41, 67,  2],
       [10, 55, 16, 25],
       [93, 94, 54, 69]])

In [90]:
# 2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.
# Con el 60 nos sale error. 
array2r = np.arange(1, 61).reshape(3, 4, 5)
array2r

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [96]:
array2Dr = array2r.reshape(-1,5)
array2Dr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [97]:
#3 .Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

array3r = np.random.rand(4,3,2)
array3r

array([[[0.70860374, 0.36637518],
        [0.81335154, 0.33833912],
        [0.92790387, 0.89495686]],

       [[0.28438384, 0.87044395],
        [0.2137098 , 0.48683291],
        [0.19809332, 0.08155711]],

       [[0.36854371, 0.09478137],
        [0.95691275, 0.32511808],
        [0.42511137, 0.2187008 ]],

       [[0.56779671, 0.07850955],
        [0.56913359, 0.13850451],
        [0.66008734, 0.72903247]]])

In [99]:
array3r2d = array3r.reshape(-1,2)
array3r2d

array([[0.70860374, 0.36637518],
       [0.81335154, 0.33833912],
       [0.92790387, 0.89495686],
       [0.28438384, 0.87044395],
       [0.2137098 , 0.48683291],
       [0.19809332, 0.08155711],
       [0.36854371, 0.09478137],
       [0.95691275, 0.32511808],
       [0.42511137, 0.2187008 ],
       [0.56779671, 0.07850955],
       [0.56913359, 0.13850451],
       [0.66008734, 0.72903247]])

In [8]:
# Ejercicios con transpose:

# Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).
array2r = np.arange(1, 61).reshape(3, 4, 5)
array2r


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [10]:
arr_transpose = np.transpose(array2r, (2, 1, 0))
arr_transpose

array([[[ 1, 21, 41],
        [ 6, 26, 46],
        [11, 31, 51],
        [16, 36, 56]],

       [[ 2, 22, 42],
        [ 7, 27, 47],
        [12, 32, 52],
        [17, 37, 57]],

       [[ 3, 23, 43],
        [ 8, 28, 48],
        [13, 33, 53],
        [18, 38, 58]],

       [[ 4, 24, 44],
        [ 9, 29, 49],
        [14, 34, 54],
        [19, 39, 59]],

       [[ 5, 25, 45],
        [10, 30, 50],
        [15, 35, 55],
        [20, 40, 60]]])

In [11]:
# Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

array3r = np.random.rand(4,3,2)
array3r


array([[[6.27421899e-01, 6.94120228e-02],
        [5.33276902e-01, 9.00133202e-01],
        [2.02784120e-02, 2.30725900e-02]],

       [[2.57370362e-01, 5.24791102e-01],
        [8.72773569e-04, 8.92578137e-01],
        [5.38275369e-01, 1.73709151e-01]],

       [[2.80291770e-01, 4.36575142e-01],
        [5.23808001e-01, 3.06785740e-01],
        [6.69792963e-01, 8.18673981e-01]],

       [[9.82208350e-02, 6.15163581e-01],
        [8.83140365e-01, 2.23171974e-01],
        [4.63225288e-01, 7.35775285e-01]]])

In [13]:
arr_transpose = np.transpose(array3r, (1, 2, 0))
arr_transpose

array([[[6.27421899e-01, 2.57370362e-01, 2.80291770e-01, 9.82208350e-02],
        [6.94120228e-02, 5.24791102e-01, 4.36575142e-01, 6.15163581e-01]],

       [[5.33276902e-01, 8.72773569e-04, 5.23808001e-01, 8.83140365e-01],
        [9.00133202e-01, 8.92578137e-01, 3.06785740e-01, 2.23171974e-01]],

       [[2.02784120e-02, 5.38275369e-01, 6.69792963e-01, 4.63225288e-01],
        [2.30725900e-02, 1.73709151e-01, 8.18673981e-01, 7.35775285e-01]]])

##### Preguntas teóricas:

##### ¿Qué diferencia existe entre el reshape y el transpose?

Reshape: cambia la forma de la matriz sin modificar sus elementos, Transpose intercambia filas y columnas de una matriz modificandolas.

##### ¿Y entre el transpose y el swapaxes?

Con swapaxes intercambias dos ejes especificos de una matriz pero mantiene los demás sin cambios.  

In [ ]:
# Funciones Aritméticas y Estadísticas:


# Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

# Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

# Si el valor del array es igual que la media, se reemplaza por "A".

# Si el valor del array es mayor que la media, se reemplaza por "B".

# Si el valor del array es menor que la media, se reemplaza por "C".

# Si el valor es igual que el máximo, se reemplaza por "D".

# Si el valor es igual que el mínimo, se reemplaza por "E".

In [2]:
arr =  np.random.random_sample((2,3,5))
arr

array([[[0.2183032 , 0.50427861, 0.46271415, 0.81613688, 0.78433281],
        [0.84773912, 0.33221529, 0.24912227, 0.30586148, 0.07734475],
        [0.08677633, 0.18916565, 0.23099974, 0.34873598, 0.9490584 ]],

       [[0.78587858, 0.63675764, 0.09800055, 0.0507819 , 0.11879946],
        [0.53516586, 0.29745318, 0.89973905, 0.57925235, 0.11420179],
        [0.18895757, 0.00270178, 0.30302946, 0.31324151, 0.52166964]]])

In [3]:
media = np.mean(arr)
max = np.max(arr)
min = np.min(arr)

In [4]:
arr[0][0][3] > media

True

In [5]:
vacio = np.empty_like(arr,dtype=str) # empty_like : la forma del otro array 
vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [6]:
for matriz in range(arr.shape[0]):
    for fila in range(arr.shape[1]):
        for col in range (arr.shape[2]):
            if arr[matriz][fila][col] == media:
                    vacio[matriz][fila][col] = "A"
            elif arr[matriz][fila][col] == max:
                    vacio[matriz][fila][col] = "D"
            elif arr[matriz][fila][col] == min:
                    vacio[matriz][fila][col] = "E"
            elif arr[matriz][fila][col] > media:
                    vacio[matriz][fila][col] = "B"
            elif arr[matriz][fila][col] < media:
                    vacio[matriz][fila][col] = "C"

In [7]:
vacio

array([[['C', 'B', 'B', 'B', 'B'],
        ['B', 'C', 'C', 'C', 'C'],
        ['C', 'C', 'C', 'C', 'D']],

       [['B', 'B', 'C', 'C', 'C'],
        ['B', 'C', 'B', 'B', 'C'],
        ['C', 'E', 'C', 'C', 'B']]], dtype='<U1')